### ISSUE TITLE
Is this ready to use ?

### ISSUE THREAD

**Issue by ramdhan1989** [iankhr/armagarch#2]
interesting repo. is this ready to use and to install ? I am using windows environment. I am excited to look for installation and doc.

thank you

regards

**Comment by iankhr** [comment]
I have uploaded the files to pip, so you can install it with
`pip install armagarch`
The documentation is still work in progress...

**Comment by MarioVeloso** [comment]
I attempted to use your package for the prediction of stock prices using the code of your example as reference. Interestingly, it seems to work fine with some stocks, but with others it generates the following error:
                 "armagarch.errors.HessianError: Hessian is singular! St.errors are not calculated"
Is there a way to overcome this problem?
Thanks in advance.
Regards,
