### ISSUE TITLE
ERROR: module 'statsmodels.tsa.api' has no attribute 'ARMA'

### ISSUE THREAD

**Issue by nikolhaas65** [iankhr/armagarch#5]
does not run

...\lib\site-packages\armagarch\ARMA.py in _getStartingVals(self)
     60                 c = 'nc'
     61             try:
---> 62                 model = sm.ARMA(self._data.values, (self._order['AR'],self._order['MA'])).fit(trend = c)
     63                 self._startingValues = model.params
     64             except ValueError:

**Comment by AlexHuang2** [comment]
[See here](https://github.com/iankhr/armagarch/pull/6#issuecomment-1183838062)

**Comment by iankhr** [comment]
Fixed from v1.0.3
